(function(){
'use strict';
const $=id=>document.getElementById(id);
const fmt=n=>new Intl.NumberFormat('es-CL').format(Math.round(Number(n)||0));
const money=n=>'$'+fmt(n);
const pct=n=>Math.round((Number(n)||0)*100)+'%';

function activeState(){try{return JSON.parse(localStorage.getItem('turnoState')||'null')}catch(e){return null}}
function people(){const s=activeState();if(s&&Array.isArray(s.crew)&&s.crew.length)return s.crew.length;const t=($('crew')&&$('crew').textContent)||'';const m=t.match(/(\d+)\s+person/);return m?+m[1]:0}
function currentKg(){const t=($('kgToday')&&$('kgToday').textContent)||'0';return Number(t.replace(/\./g,'').replace(',','.').replace(/[^0-9.-]/g,''))||0}
function cfg(){return window.BONUS_CFG||window.BONUS_CONFIG_DEFAULTS||null}
function raw(kg,p,c){const scale=c.scale&&c.scale[p]?Number(c.scale[p]):1,labor=p*c.cost,sav=Math.max(0,(c.target*scale)*kg-labor),th=c.thresholdKg[p];if(!th||kg<th[1]||sav<=0)return{sav,share:0,pozo:0,li:-1};let li=-1;th.forEach((v,i)=>{if(kg>=v)li=i});const share=li>=2?c.shares[Math.min(li-1,3)]:c.shares[0];return{sav,share,pozo:sav*share,li}}
function eff(kg,p,c){const th=c.thresholdKg[p],r=raw(kg,p,c);let pozo=r.pozo;[2,3,4].forEach(i=>{if(kg>=th[i])pozo=Math.max(pozo,raw(Math.max(0,th[i]-c.eqKg),p,c).pozo)});return{...r,pozo,frozen:pozo>r.pozo+.5}}
function level(kg,p,c){const t=c.thresholdKg[p];if(kg<t[0])return'Bajo Base';if(kg<t[1])return'Base';if(kg<t[2])return'N1';if(kg<t[3])return'N2';if(kg<t[4])return'N3';return'N4'}
function rowData(kg,p,c){const scale=c.scale&&c.scale[p]?Number(c.scale[p]):1,labor=p*c.cost,r=eff(kg,p,c),gross=p?r.pozo/p:0,liq=gross*c.net,final=kg?(labor+r.pozo)/kg:0,company=Math.max(0,r.sav-r.pozo);return{scale,r,gross,liq,final,company}}

function css(){if($('activeToolsCss'))return;const s=document.createElement('style');s.id='activeToolsCss';s.textContent=`
.atActions{display:flex;gap:7px;justify-content:flex-end;flex-wrap:wrap;margin-top:6px}.atBtn{border:1px solid var(--line2);background:transparent;color:var(--muted2);border-radius:12px;padding:11px 14px;font:600 11px Oswald;letter-spacing:.12em;text-transform:uppercase;cursor:pointer;min-height:44px}.atBtn.open{border-color:var(--agua);color:var(--agua)}.atBtn.back{color:var(--muted)}
.atPanel{display:none;background:var(--card);border:1px solid var(--line);border-radius:18px;margin-bottom:16px;overflow:hidden}.atPanel.on{display:block}.atHead{display:flex;justify-content:space-between;gap:12px;align-items:center;padding:15px 17px;border-bottom:1px solid var(--line)}.atHead h3{margin:0;font:700 20px Oswald;text-transform:uppercase}.atHead small{display:block;color:var(--muted);font-size:11px;margin-top:3px}.atClose{border:1px solid var(--line2);background:transparent;color:var(--muted2);border-radius:10px;padding:9px 12px;cursor:pointer}.atScroll{overflow:auto;max-height:470px}.atTable{width:100%;border-collapse:collapse;min-width:980px}.atTable th{position:sticky;top:0;background:#171c1d;z-index:2;font:600 9px Oswald;letter-spacing:.12em;text-transform:uppercase;color:var(--muted);padding:10px 8px;text-align:right;border-bottom:1px solid var(--line)}.atTable th:first-child,.atTable td:first-child{text-align:left}.atTable td{padding:9px 8px;border-bottom:1px solid var(--line);font-size:11px;text-align:right;white-space:nowrap}.atTable tr.current td{background:#202b25}.atTable tr.milestone td{border-top:1px solid var(--line2)}.atLiq{color:var(--lime);font-weight:800}.atLevel{display:inline-block;border:1px solid var(--line2);border-radius:999px;padding:3px 7px;font:600 9px Oswald}.atNow{color:var(--agua);font:700 9px Oswald;margin-left:5px;text-transform:uppercase}
.atResume{display:none;border:1px solid var(--agua);background:linear-gradient(135deg,#15201d,var(--card));border-radius:16px;padding:14px 16px;margin-bottom:14px;align-items:center;justify-content:space-between;gap:12px}.atResume.on{display:flex}.atResume b{font:600 15px Oswald;text-transform:uppercase}.atResume span{display:block;color:var(--muted2);font-size:11px;margin-top:3px}.atResume button{border:0;background:var(--agua);color:#0c0e0f;border-radius:11px;padding:11px 15px;font:700 11px Oswald;letter-spacing:.12em;text-transform:uppercase;cursor:pointer;min-height:44px}
@media(max-width:640px){.atActions{justify-content:flex-end}.atBtn{padding:10px 11px}.atResume{align-items:flex-start;flex-direction:column}.atResume button{width:100%}}
`;document.head.appendChild(s)}

function renderOpening(){const panel=$('activeOpeningPanel'),body=$('activeOpeningBody'),meta=$('activeOpeningMeta');if(!panel||!body||!meta)return;const c=cfg(),p=people();if(!c||!p||!c.thresholdKg||!c.thresholdKg[p]){body.innerHTML='<tr><td colspan="10">No hay configuración para este número de personas.</td></tr>';return}const t=c.thresholdKg[p],step=Math.max(1,Number(c.eqKg)||15),from=t[0],to=t[4],now=currentKg(),currentEq=now/step,rows=[];let kg=Math.ceil(from/step)*step;if(Math.abs(kg-from)>.001)rows.push(from);for(;kg<=to+.001;kg+=step)rows.push(kg);if(!rows.length||Math.abs(rows[rows.length-1]-to)>.001)rows.push(to);const milestones=new Set(t.map(Number));body.innerHTML=rows.map(k=>{const d=rowData(k,p,c),eq=k/step,isCurrent=Math.abs(eq-currentEq)<.5;return `<tr class="${isCurrent?'current ':''}${milestones.has(Number(k))?'milestone':''}"><td><b>${Number.isInteger(eq)?fmt(eq):eq.toFixed(1).replace('.',',')}</b>${isCurrent?'<span class="atNow">ahora</span>':''}</td><td>${fmt(k)}</td><td><span class="atLevel">${level(k,p,c)}</span></td><td>${d.r.share?pct(d.r.share):'—'}</td><td>${money(d.r.sav)}</td><td>${money(d.r.pozo)}</td><td class="atLiq">${money(d.liq)}</td><td>${money(d.gross)}</td><td>${money(d.final)}</td><td>${money(d.company)}</td></tr>`}).join('');const sc=c.scale&&c.scale[p]?Number(c.scale[p]):1;meta.textContent=`${p} personas · factor bono ${Math.round(sc*100)}% · ${fmt(from/step)} a ${fmt(to/step)} mallas eq.`;if(panel.classList.contains('on')){const cur=body.querySelector('tr.current');if(cur)setTimeout(()=>cur.scrollIntoView({block:'center',behavior:'smooth'}),40)}}

function mount(){css();const main=$('main'),setup=$('setup');if(!main||!setup)return;
  const top=main.querySelector('.topbar');if(top&&!$('activeOpeningBtn')){const right=top.lastElementChild;const oldEnd=$('endBtn');const actions=document.createElement('div');actions.className='atActions';if(oldEnd){oldEnd.style.marginTop='0';actions.appendChild(oldEnd)}const open=document.createElement('button');open.id='activeOpeningBtn';open.className='atBtn open';open.type='button';open.textContent='Ver apertura';const back=document.createElement('button');back.id='activeBackBtn';back.className='atBtn back';back.type='button';back.textContent='← Volver';actions.appendChild(open);actions.appendChild(back);right.appendChild(actions);
    const panel=document.createElement('div');panel.id='activeOpeningPanel';panel.className='atPanel';panel.innerHTML='<div class="atHead"><div><h3>Apertura del turno</h3><small id="activeOpeningMeta"></small></div><button class="atClose" id="activeOpeningClose" type="button">Cerrar</button></div><div class="atScroll"><table class="atTable"><thead><tr><th>Malla eq.</th><th>kg</th><th>Nivel</th><th>% equipo</th><th>Ahorro</th><th>Pozo equipo</th><th>Líquido/persona</th><th>Bruto/persona</th><th>Costo final/kg</th><th>Empresa</th></tr></thead><tbody id="activeOpeningBody"></tbody></table></div>';top.insertAdjacentElement('afterend',panel);
    open.onclick=()=>{panel.classList.toggle('on');open.textContent=panel.classList.contains('on')?'Cerrar apertura':'Ver apertura';if(panel.classList.contains('on'))renderOpening()};$('activeOpeningClose').onclick=()=>{panel.classList.remove('on');open.textContent='Ver apertura'};
    back.onclick=()=>{panel.classList.remove('on');main.style.display='none';setup.style.display='block';showResume(true);window.scrollTo(0,0)};
  }
  if(!$('activeResume')){const d=document.createElement('div');d.id='activeResume';d.className='atResume';d.innerHTML='<div><b>Turno en curso</b><span>La producción quedó guardada. Puedes volver sin perder lo registrado.</span></div><button id="activeResumeBtn" type="button">Retomar turno</button>';const start=$('startBtn');if(start)start.insertAdjacentElement('beforebegin',d);$('activeResumeBtn').onclick=()=>{setup.style.display='none';main.style.display='block';showResume(false);renderOpening();window.scrollTo(0,0)}}
  const kg=$('kgToday');if(kg&&!kg.dataset.atObs){kg.dataset.atObs='1';new MutationObserver(()=>{if($('activeOpeningPanel')&&$('activeOpeningPanel').classList.contains('on'))renderOpening()}).observe(kg,{childList:true,characterData:true,subtree:true})}
}
function showResume(on){const d=$('activeResume');if(d)d.classList.toggle('on',!!on&&!!activeState())}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();