(function(){
'use strict';
const PENDING='theIcePendingFinalInventoryV1';
const $=id=>document.getElementById(id);
const fmt=n=>new Intl.NumberFormat('es-CL').format(Math.round(n||0));
const products=()=>Array.isArray(window.THE_ICE_PRODUCTS)&&window.THE_ICE_PRODUCTS.length?window.THE_ICE_PRODUCTS:[
  {id:'original15',name:'Pack 15 kg',tag:'Original',kg:15,bonus:true},
  {id:'original12',name:'Pack 12 kg',tag:'Original',kg:12,bonus:true},
  {id:'mini15',name:'Pack 15 kg',tag:'Mini',kg:15,bonus:true},
  {id:'saco20',name:'Saco 20 kg',tag:'Reserva',kg:20,bonus:false}
];
let allowEnd=false;
function css(){const s=document.createElement('style');s.textContent=`
.finalInvOverlay{position:fixed;inset:0;background:rgba(0,0,0,.78);z-index:120;display:none;align-items:center;justify-content:center;padding:18px;backdrop-filter:blur(6px)}.finalInvOverlay.show{display:flex}.finalInvCard{width:min(820px,100%);max-height:92vh;overflow:auto;background:var(--card);border:1px solid var(--line2);border-radius:22px;padding:22px;box-shadow:0 24px 80px rgba(0,0,0,.45)}.finalInvCard h2{font:700 30px Oswald;margin:0;text-transform:uppercase}.finalInvCard h2 em{font-style:normal;color:var(--lime)}.finalInvCard .sub{color:var(--muted2);font-size:13px;line-height:1.5;margin:6px 0 18px}.finalInvGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.finalInvBox{background:var(--card2);border:1px solid var(--line);border-radius:16px;padding:14px}.finalInvBox b{display:block;font-family:Oswald;font-size:15px;text-transform:uppercase}.finalInvBox small{display:block;color:var(--muted);margin:3px 0 10px}.finalInvBox input{width:100%;background:var(--input);border:1px solid var(--line2);color:var(--text);border-radius:10px;padding:13px;text-align:center;font:600 26px Oswald}.stockOnly{display:inline-block;margin-top:5px;border:1px solid #49675e;color:var(--agua);border-radius:999px;padding:3px 7px;font:600 9px Oswald;letter-spacing:.08em;text-transform:uppercase}.finalInvTotal{display:flex;justify-content:space-between;gap:12px;align-items:center;margin:16px 0;padding:14px;border:1px solid var(--line);border-radius:14px}.finalInvTotal span{color:var(--muted);font:600 11px Oswald;letter-spacing:.14em;text-transform:uppercase}.finalInvTotal b{font:600 22px Oswald;color:var(--lime)}.finalInvActions{display:grid;grid-template-columns:1fr 1fr;gap:10px}.finalInvActions button{min-height:52px;border-radius:13px;font:600 12px Oswald;letter-spacing:.14em;text-transform:uppercase;cursor:pointer}.finalInvGo{background:var(--lime);border:1px solid var(--lime);color:#0c0e0f}.finalInvCancel{background:transparent;border:1px solid var(--line2);color:var(--muted2)}.dayInvCard{margin-bottom:16px}.dayInvGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:12px}.dayInvItem{background:var(--card2);border:1px solid var(--line);border-radius:13px;padding:13px}.dayInvItem span{display:block;color:var(--muted);font-size:11px}.dayInvItem b{font:600 23px Oswald;color:var(--lime)}.dayInvMeta{color:var(--muted2);font-size:12px;margin-top:10px}@media(max-width:640px){.finalInvGrid,.dayInvGrid{grid-template-columns:1fr}.finalInvActions{grid-template-columns:1fr}}
`;document.head.appendChild(s)}
function hideInitialInventory(){const inv0=$('inv0');if(inv0){const card=inv0.closest('.card');if(card)card.style.display='none'}const meta=$('invNowTotal');if(meta&&meta.closest('.metaBox'))meta.closest('.metaBox').style.display='none';document.querySelectorAll('.invNow').forEach(x=>x.style.display='none');const strip=document.querySelector('.metaStrip');if(strip)strip.style.gridTemplateColumns='repeat(3,1fr)'}
function buildModal(){let d=$('finalInvOverlay');if(d)d.remove();const ps=products();d=document.createElement('div');d.id='finalInvOverlay';d.className='finalInvOverlay';d.innerHTML=`<div class="finalInvCard"><h2>Inventario <em>final</em></h2><p class="sub">Cuenta lo que queda físicamente en bodega al terminar el turno. Los productos de reserva también se registran, aunque no cuenten para el bono.</p><div class="finalInvGrid">${ps.map((p,i)=>`<div class="finalInvBox"><b>${p.name}</b><small>${p.tag||'Producto'} · ${p.kg} kg por unidad</small>${p.bonus?'':'<span class="stockOnly">Sólo inventario</span>'}<input id="finInv${i}" type="number" min="0" step="1" value="0" inputmode="numeric"><small id="finKg${i}">0 kg</small></div>`).join('')}</div><div class="finalInvTotal"><span>Total inventario final</span><b id="finInvTotal">0 unidades · 0 kg</b></div><div class="finalInvActions"><button class="finalInvCancel" id="finInvCancel">Volver al turno</button><button class="finalInvGo" id="finInvGo">Continuar al cierre</button></div></div>`;document.body.appendChild(d);const update=()=>{let u=0,kg=0;ps.forEach((p,i)=>{const n=Math.max(0,Math.floor(+$('finInv'+i).value||0));u+=n;kg+=n*p.kg;$('finKg'+i).textContent=fmt(n*p.kg)+' kg'});$('finInvTotal').textContent=fmt(u)+' unidades · '+fmt(kg)+' kg'};ps.forEach((_,i)=>$('finInv'+i).addEventListener('input',update));$('finInvCancel').onclick=()=>d.classList.remove('show');$('finInvGo').onclick=()=>{const items=ps.map((p,i)=>{const units=Math.max(0,Math.floor(+$('finInv'+i).value||0));return{id:p.id,name:p.name,tag:p.tag,kgPerUnit:p.kg,bonus:!!p.bonus,units,kg:units*p.kg}});const payload={capturedAt:Date.now(),items,totalUnits:items.reduce((a,x)=>a+x.units,0),totalKg:items.reduce((a,x)=>a+x.kg,0)};localStorage.setItem(PENDING,JSON.stringify(payload));d.classList.remove('show');allowEnd=true;$('endBtn').click();allowEnd=false};return d}
function pending(){try{return JSON.parse(localStorage.getItem(PENDING)||'null')}catch(e){return null}}
function patchLocalHistory(){const inv=pending();if(!inv)return;try{const h=JSON.parse(localStorage.getItem('turnoHistory')||'[]');if(Array.isArray(h)&&h.length){h[h.length-1].finalInventory=inv;localStorage.setItem('turnoHistory',JSON.stringify(h))}}catch(e){}localStorage.removeItem(PENDING)}
async function renderDayInventory(){const host=$('dayFinalInventory');if(!host)return;let rows=[];try{const r=await fetch('/api/turnos',{cache:'no-store'});if(r.ok){const j=await r.json();if(Array.isArray(j))rows=j}}catch(e){}if(!rows.length){try{const j=JSON.parse(localStorage.getItem('turnoHistory')||'[]');if(Array.isArray(j))rows=j}catch(e){}}const today=new Date(),key=today.getFullYear()+'-'+String(today.getMonth()+1).padStart(2,'0')+'-'+String(today.getDate()).padStart(2,'0');const sameDay=rows.filter(r=>{const d=new Date(r.ts);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')===key&&r.finalInventory});if(!sameDay.length){host.innerHTML='<div style="color:var(--muted);font-size:13px;padding:8px 0">Todavía no hay un inventario final registrado hoy.</div>';return}sameDay.sort((a,b)=>a.ts-b.ts);const last=sameDay[sameDay.length-1],inv=last.finalInventory;host.innerHTML=`<div class="dayInvGrid">${(inv.items||[]).map(x=>`<div class="dayInvItem"><span>${x.name}${x.tag?' · '+x.tag:''}${x.bonus===false?' · reserva':''}</span><b>${fmt(x.units)}</b><span>${fmt(x.kg)} kg</span></div>`).join('')}</div><div class="dayInvMeta">Último cierre informado hoy · ${new Date(inv.capturedAt||last.ts).toLocaleTimeString('es-CL',{hour:'2-digit',minute:'2-digit'})} · Total ${fmt(inv.totalUnits)} unidades / ${fmt(inv.totalKg)} kg</div>`}
function addReportModule(){const hist=$('histList');if(!hist)return;const card=hist.closest('.card');if(!card||$('dayFinalInventory'))return;const d=document.createElement('div');d.className='card dayInvCard';d.innerHTML='<p class="sec">Inventario final del día</p><p class="secSub">Último inventario informado en un cierre de hoy, por producto.</p><div id="dayFinalInventory"></div>';card.parentNode.insertBefore(d,card)}
function hook(){const end=$('endBtn');if(end)end.addEventListener('click',e=>{if(allowEnd)return;e.preventDefault();e.stopImmediatePropagation();buildModal().classList.add('show')},true);const save=$('saveBtn');if(save)save.addEventListener('click',()=>setTimeout(patchLocalHistory,0));const rep=$('repBtn');if(rep)rep.addEventListener('click',()=>setTimeout(renderDayInventory,80));window.addEventListener('theiceproductschange',()=>{if($('finalInvOverlay'))buildModal()})}
const nativeFetch=window.fetch.bind(window);window.fetch=(input,init)=>{try{const url=typeof input==='string'?input:(input&&input.url)||'';if(url.includes('/api/turnos')&&init&&String(init.method||'GET').toUpperCase()==='POST'&&init.body){const inv=pending();if(inv){const body=JSON.parse(init.body);body.finalInventory=inv;init={...init,body:JSON.stringify(body)}}}}catch(e){}return nativeFetch(input,init)};
document.addEventListener('DOMContentLoaded',()=>{css();hideInitialInventory();buildModal();addReportModule();hook()});
})();