(function(){
'use strict';
const PENDING='theIcePendingFinalInventoryV1';
const $=id=>document.getElementById(id);
const fmt=n=>new Intl.NumberFormat('es-CL').format(Math.round(n||0));
const products=()=>Array.isArray(window.THE_ICE_PRODUCTS)&&window.THE_ICE_PRODUCTS.length?window.THE_ICE_PRODUCTS:[
  {id:'original15',name:'Pack 15 kg',tag:'Original',kg:15,bonus:true},
  {id:'original12',name:'Pack 12 kg',tag:'Original',kg:12,bonus:true},
  {id:'mini15',name:'Pack 15 kg',tag:'Mini',kg:15,bonus:true},
  {id:'saco20',name:'Saco 20 kg',tag:'Reserva',kg:20,bonus:false}
];
let allowEnd=false;
function shiftName(ts){const h=new Date(ts).getHours();if(h>=7&&h<16)return'AM';if(h>=16&&h<22)return'Extensión';return'Nocturno'}
function css(){const s=document.createElement('style');s.textContent=`
.finalInvOverlay{position:fixed;inset:0;background:rgba(0,0,0,.78);z-index:120;display:none;align-items:center;justify-content:center;padding:18px;backdrop-filter:blur(6px)}.finalInvOverlay.show{display:flex}.finalInvCard{width:min(820px,100%);max-height:92vh;overflow:auto;background:var(--card);border:1px solid var(--line2);border-radius:22px;padding:22px;box-shadow:0 24px 80px rgba(0,0,0,.45)}.finalInvCard h2{font:700 30px Oswald;margin:0;text-transform:uppercase}.finalInvCard h2 em{font-style:normal;color:var(--lime)}.finalInvCard .sub{color:var(--muted2);font-size:13px;line-height:1.5;margin:6px 0 18px}.finalInvGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.finalInvBox{background:var(--card2);border:1px solid var(--line);border-radius:16px;padding:14px}.finalInvBox b{display:block;font-family:Oswald;font-size:15px;text-transform:uppercase}.finalInvBox small{display:block;color:var(--muted);margin:3px 0 10px}.finalInvBox input{width:100%;background:var(--input);border:1px solid var(--line2);color:var(--text);border-radius:10px;padding:13px;text-align:center;font:600 26px Oswald}.stockOnly{display:inline-block;margin-top:5px;border:1px solid #49675e;color:var(--agua);border-radius:999px;padding:3px 7px;font:600 9px Oswald;letter-spacing:.08em;text-transform:uppercase}.finalInvTotal{display:flex;justify-content:space-between;gap:12px;align-items:center;margin:16px 0;padding:14px;border:1px solid var(--line);border-radius:14px}.finalInvTotal span{color:var(--muted);font:600 11px Oswald;letter-spacing:.14em;text-transform:uppercase}.finalInvTotal b{font:600 22px Oswald;color:var(--lime)}.finalInvActions{display:grid;grid-template-columns:1fr 1fr;gap:10px}.finalInvActions button{min-height:52px;border-radius:13px;font:600 12px Oswald;letter-spacing:.14em;text-transform:uppercase;cursor:pointer}.finalInvGo{background:var(--lime);border:1px solid var(--lime);color:#0c0e0f}.finalInvCancel{background:transparent;border:1px solid var(--line2);color:var(--muted2)}
.dayInvCard{margin-bottom:16px}.invChart{display:flex;align-items:flex-end;justify-content:center;gap:28px;height:230px;padding:24px 18px 0;border-bottom:1px solid var(--line);margin-top:12px}.invCol{height:100%;width:min(170px,34%);display:flex;flex-direction:column;justify-content:flex-end;align-items:center;cursor:pointer}.invBar{width:100%;min-height:8px;border-radius:12px 12px 4px 4px;display:flex;align-items:flex-start;justify-content:center;padding-top:8px;font:700 13px Oswald;color:#0c0e0f;transition:.18s transform}.invCol:hover .invBar{transform:translateY(-3px)}.invBar.am{background:var(--lime)}.invBar.night{background:var(--agua)}.invBar.ext{background:var(--coral)}.invColLab{font:600 12px Oswald;letter-spacing:.08em;text-transform:uppercase;margin-top:9px}.invColMeta{font-size:10px;color:var(--muted);margin-top:3px}.invDetail{margin-top:14px;padding:14px;background:var(--card2);border:1px solid var(--line);border-radius:14px}.invDetailHead{display:flex;justify-content:space-between;gap:10px;margin-bottom:10px}.invDetailHead b{font:700 18px Oswald}.dayInvGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.dayInvItem{background:var(--card);border:1px solid var(--line);border-radius:11px;padding:11px}.dayInvItem span{display:block;color:var(--muted);font-size:10px}.dayInvItem b{font:600 20px Oswald;color:var(--lime)}.dayInvMeta{color:var(--muted2);font-size:11px;margin-top:10px}.invEmpty{color:var(--muted);font-size:13px;padding:8px 0}@media(max-width:640px){.finalInvGrid,.dayInvGrid{grid-template-columns:1fr 1fr}.finalInvActions{grid-template-columns:1fr}.invChart{gap:14px}.invCol{width:42%}}
`;document.head.appendChild(s)}
function hideInitialInventory(){const inv0=$('inv0');if(inv0){const card=inv0.closest('.card');if(card)card.style.display='none'}const meta=$('invNowTotal');if(meta&&meta.closest('.metaBox'))meta.closest('.metaBox').style.display='none';document.querySelectorAll('.invNow').forEach(x=>x.style.display='none');const strip=document.querySelector('.metaStrip');if(strip)strip.style.gridTemplateColumns='repeat(3,1fr)'}
function buildModal(){let d=$('finalInvOverlay');if(d)d.remove();const ps=products();d=document.createElement('div');d.id='finalInvOverlay';d.className='finalInvOverlay';d.innerHTML=`<div class="finalInvCard"><h2>Inventario <em>final</em></h2><p class="sub">Cuenta lo que queda físicamente en bodega al terminar el turno. Los productos de reserva también se registran, aunque no cuenten para el bono.</p><div class="finalInvGrid">${ps.map((p,i)=>`<div class="finalInvBox"><b>${p.name}</b><small>${p.tag||'Producto'} · ${p.kg} kg por unidad</small>${p.bonus?'':'<span class="stockOnly">Sólo inventario</span>'}<input id="finInv${i}" type="number" min="0" step="1" value="0" inputmode="numeric"><small id="finKg${i}">0 kg</small></div>`).join('')}</div><div class="finalInvTotal"><span>Total inventario final</span><b id="finInvTotal">0 unidades · 0 kg</b></div><div class="finalInvActions"><button class="finalInvCancel" id="finInvCancel">Volver al turno</button><button class="finalInvGo" id="finInvGo">Continuar al cierre</button></div></div>`;document.body.appendChild(d);const update=()=>{let u=0,kg=0;ps.forEach((p,i)=>{const n=Math.max(0,Math.floor(+$('finInv'+i).value||0));u+=n;kg+=n*p.kg;$('finKg'+i).textContent=fmt(n*p.kg)+' kg'});$('finInvTotal').textContent=fmt(u)+' unidades · '+fmt(kg)+' kg'};ps.forEach((_,i)=>$('finInv'+i).addEventListener('input',update));$('finInvCancel').onclick=()=>d.classList.remove('show');$('finInvGo').onclick=()=>{const items=ps.map((p,i)=>{const units=Math.max(0,Math.floor(+$('finInv'+i).value||0));return{id:p.id,name:p.name,tag:p.tag,kgPerUnit:p.kg,bonus:!!p.bonus,units,kg:units*p.kg}});const payload={capturedAt:Date.now(),items,totalUnits:items.reduce((a,x)=>a+x.units,0),totalKg:items.reduce((a,x)=>a+x.kg,0)};localStorage.setItem(PENDING,JSON.stringify(payload));d.classList.remove('show');allowEnd=true;$('endBtn').click();allowEnd=false};return d}
function pending(){try{return JSON.parse(localStorage.getItem(PENDING)||'null')}catch(e){return null}}
function patchLocalHistory(){const inv=pending();if(!inv)return;try{const h=JSON.parse(localStorage.getItem('turnoHistory')||'[]');if(Array.isArray(h)&&h.length){h[h.length-1].finalInventory=inv;h[h.length-1].shift=shiftName(h[h.length-1].ts);localStorage.setItem('turnoHistory',JSON.stringify(h))}}catch(e){}localStorage.removeItem(PENDING)}
function dayKey(ts){const d=new Date(ts);/* nocturno que termina después de medianoche pertenece al día en que comenzó */if(d.getHours()<7)d.setDate(d.getDate()-1);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function detailHtml(rec){const inv=rec.finalInventory||{items:[]};return `<div class="invDetailHead"><b>Turno ${rec.shift||shiftName(rec.ts)}</b><span>${new Date(inv.capturedAt||rec.ts).toLocaleTimeString('es-CL',{hour:'2-digit',minute:'2-digit'})}</span></div><div class="dayInvGrid">${(inv.items||[]).map(x=>`<div class="dayInvItem"><span>${x.name}${x.tag?' · '+x.tag:''}${x.bonus===false?' · reserva':''}</span><b>${fmt(x.units)}</b><span>${fmt(x.kg)} kg</span></div>`).join('')}</div><div class="dayInvMeta">Total informado: ${fmt(inv.totalUnits)} unidades · ${fmt(inv.totalKg)} kg</div>`}
async function renderDayInventory(){const host=$('dayFinalInventory');if(!host)return;let rows=[];try{const r=await fetch('/api/turnos',{cache:'no-store'});if(r.ok){const j=await r.json();if(Array.isArray(j))rows=j}}catch(e){}if(!rows.length){try{const j=JSON.parse(localStorage.getItem('turnoHistory')||'[]');if(Array.isArray(j))rows=j}catch(e){}}const now=new Date(),key=now.getFullYear()+'-'+String(now.getMonth()+1).padStart(2,'0')+'-'+String(now.getDate()).padStart(2,'0');const same=rows.filter(r=>r.finalInventory&&dayKey(r.ts)===key).map(r=>({...r,shift:r.shift||shiftName(r.ts)})).sort((a,b)=>a.ts-b.ts);if(!same.length){host.innerHTML='<div class="invEmpty">Todavía no hay inventarios finales registrados para hoy.</div>';return}const order=['AM','Extensión','Nocturno'];const latest={};same.forEach(r=>latest[r.shift]=r);const visible=order.filter(k=>latest[k]);const max=Math.max(...visible.map(k=>latest[k].finalInventory.totalKg||0),1);host.innerHTML=`<div class="invChart">${visible.map(k=>{const r=latest[k],kg=r.finalInventory.totalKg||0,cl=k==='AM'?'am':k==='Nocturno'?'night':'ext';return `<div class="invCol" data-shift="${k}"><div class="invBar ${cl}" style="height:${Math.max(8,kg/max*180)}px">${fmt(kg)} kg</div><div class="invColLab">${k}</div><div class="invColMeta">${fmt(r.finalInventory.totalUnits)} unidades</div></div>`}).join('')}</div><div id="invShiftDetail" class="invDetail">${detailHtml(latest[visible[0]])}</div>`;host.querySelectorAll('.invCol').forEach(el=>el.onclick=()=>{$('invShiftDetail').innerHTML=detailHtml(latest[el.dataset.shift])})}
function addReportModule(){const hist=$('histList');if(!hist)return;const card=hist.closest('.card');if(!card||$('dayFinalInventory'))return;const d=document.createElement('div');d.className='card dayInvCard';d.innerHTML='<p class="sec">Inventario final por turno</p><p class="secSub">Comparación del stock informado al cierre. AM 07:30–16:00 · Nocturno 22:00–07:30. Pincha una barra para ver el detalle por producto.</p><div id="dayFinalInventory"></div>';card.parentNode.insertBefore(d,card)}
function hook(){const end=$('endBtn');if(end)end.addEventListener('click',e=>{if(allowEnd)return;e.preventDefault();e.stopImmediatePropagation();buildModal().classList.add('show')},true);const save=$('saveBtn');if(save)save.addEventListener('click',()=>setTimeout(patchLocalHistory,0));const rep=$('repBtn');if(rep)rep.addEventListener('click',()=>setTimeout(renderDayInventory,100));window.addEventListener('theiceproductschange',()=>{if($('finalInvOverlay'))buildModal()})}
const nativeFetch=window.fetch.bind(window);window.fetch=(input,init)=>{try{const url=typeof input==='string'?input:(input&&input.url)||'';if(url.includes('/api/turnos')&&init&&String(init.method||'GET').toUpperCase()==='POST'&&init.body){const inv=pending();if(inv){const body=JSON.parse(init.body);body.finalInventory=inv;body.shift=shiftName(body.ts||Date.now());init={...init,body:JSON.stringify(body)}}}}catch(e){}return nativeFetch(input,init)};
document.addEventListener('DOMContentLoaded',()=>{css();hideInitialInventory();buildModal();addReportModule();hook()});
})();